mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-handlers-package: top.zhacker.sample.retail.online.item.domain.mybatis

swagger:
  basePackage: top.zhacker.sample.retail.online.item.rest.item
server:
  port: 9002
spring:
  application:
    name: retail-online
  datasource:
    url: jdbc:mysql://localhost:3306/retail?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: anywhere
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring.cloud.sentinel.transport.dashboard: localhost:8080