spring:
  application:
    name: agile
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:/tmp/agilepmdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    continue-on-error: true
    schema: classpath:schema.sql
    initialization-mode: always
  cloud:
    refresh:
      refreshable: none

app.name: agile
server:
  port: 8081

leveldb.path: /tmp/agiledb

event.store: leveldb
event.publish.tracker: leveldb
event.process.tracker: leveldb

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

swagger.basePackage: top.zhacker.ddd.agilepm.api